package com.xworkz.collect.dtoRunner;

import com.xworkz.collect.dto.MlaDTO;

import java.util.ArrayList;
import java.util.Collection;
import java.util.stream.Collectors;

public class MlaDTORunner {

	public static void main(String[] args) {

		MlaDTO mla1 = new MlaDTO("Shahikala Jolle", 40, "Nippani", "BJP", false, "Female");
		MlaDTO mla2 = new MlaDTO("Ganesh Hukkeri", 45, "Chikkodi-Sadalaga", "INC", false, "Male");
		MlaDTO mla3 = new MlaDTO("Mahesh Kumathalli", 55, "Athani", "BJP", false, "Male");
		MlaDTO mla4 = new MlaDTO("Srimanth Patil", 45, "Kagawad", "BJP", false, "Male");
		MlaDTO mla5 = new MlaDTO("P.Rajeev", 56, "Kudachi", "BJP", false, "Male");
		MlaDTO mla6 = new MlaDTO("Duryodhan M Aihole", 46, "Rayabag", "BJP", false, "Male");
		MlaDTO mla7 = new MlaDTO("Umesh Katti", 65, "Hukkeri", "BJP", false, "Male");
		MlaDTO mla8 = new MlaDTO("Balachandra Jarakiholi", 63, "Arabhavi", "BJP", false, "Male");
		MlaDTO mla9 = new MlaDTO("Ramesh Jarakiholi", 44, "Gokak", "BJP", false, "Male");
		MlaDTO mla10 = new MlaDTO("Satish Jarakiholi", 45, "Yemakanamaradi", "INC", false, "Male");
		MlaDTO mla11 = new MlaDTO("Anil S Benake ", 46, "Belagavi Uttar", "BJP", false, "Male");
		MlaDTO mla12 = new MlaDTO("Abhay Patil", 46, "Belagavi Dakshina", "BJP", false, "Male");
		MlaDTO mla13 = new MlaDTO("Lakshmi Hebbalkar", 53, "Belagavi Rural", "INC", false, "Female");
		MlaDTO mla14 = new MlaDTO("Anjali Nimbalkar", 56, "Khanapur", "INC", false, "Female");
		MlaDTO mla15 = new MlaDTO("D. M. Basavantaray", 45, "Kittur", "BJP", false, "Male");
		MlaDTO mla16 = new MlaDTO("Mahantesh Kaujlagi", 53, "Bailhongal", "INC", false, "Male");
		MlaDTO mla17 = new MlaDTO("Anand Mamani", 55, "Saundatti Yellamma", "BJP", false, "Male");
		MlaDTO mla18 = new MlaDTO("Mahadevappa S Yadawad", 65, "Ramdurg", "BJP", false, "Male");
		MlaDTO mla19 = new MlaDTO("Govind M. Karjol", 65, "Mudhol", "BJP", false, "Male");
		MlaDTO mla20 = new MlaDTO("Siddu Savadi", 58, "Terdal", "BJP", false, "Male");
		MlaDTO mla21 = new MlaDTO("Anand Nyamagouda", 57, "Jamkhandi", "INC", false, "Male");
		MlaDTO mla22 = new MlaDTO("Murugesh Nirani", 53, "Bilgi", "BJP", false, "Male");
		MlaDTO mla23 = new MlaDTO("Siddaramaiah", 59, "Badami", "INC", false, "Male");
		MlaDTO mla24 = new MlaDTO("Veerabhadrayya Charantimath", 52, "Bagalkot", "BJP", false, "Male");
		MlaDTO mla25 = new MlaDTO("Doddanagowda Patil", 53, "Hungund", "BJP", false, "Male");
		MlaDTO mla26 = new MlaDTO("A. S. Patil", 56, "Muddebihal", "BJP", false, "Male");
		MlaDTO mla27 = new MlaDTO("Somanagouda Pati", 49, "Devar Hippargi", "BJP", false, "Male");
		MlaDTO mla28 = new MlaDTO("Shivanand S Patil", 35, "Basavana Bagevadi", "INC", false, "Male");
		MlaDTO mla29 = new MlaDTO("M. B. Patil", 48, "Babaleshwar", "INC", false, "Male");
		MlaDTO mla30 = new MlaDTO("Basangouda Patil Yatnal", 65, "Bijapur City", "BJP", false, "Male");
		MlaDTO mla31 = new MlaDTO("Devanand Fulasing Chavan", 63, "Nagathan", "JDS", false, "Male");
		MlaDTO mla32 = new MlaDTO("Y. V. Patil", 67, "Indi", "INC", false, "Male");
		MlaDTO mla33 = new MlaDTO("Ramesh B Bhusanur", 56, "Sindagi", "BJP", false, "Male");
		MlaDTO mla34 = new MlaDTO("M. Y. Patil", 65, "Afzalpur", "INC", false, "Male");
		MlaDTO mla35 = new MlaDTO("Ajay Dharam Singh", 56, "Jevargi", "INC", false, "Male");
		MlaDTO mla36 = new MlaDTO("Rajkumar Patil", 37, "Sedam", "BJP", false, "Male");
		MlaDTO mla37 = new MlaDTO("Avinash Jadhav", 48, "Chincholi", "BJP", false, "Male");
		MlaDTO mla38 = new MlaDTO("Basavaraj Mattimud", 42, "Gulbarga Rural", "BJP", false, "Male");
		MlaDTO mla39 = new MlaDTO("Dattatraya C. Patil Revoor", 46, "Gulbarga Dakshina", "BJP", false, "Male");
		MlaDTO mla40 = new MlaDTO("Kaneez Fatima", 41, "Gulbarga Uttar", "INC", false, "Female");
		MlaDTO mla41 = new MlaDTO("Guttedar Subhash Rukmayya", 49, "Aland", "BJP", false, "Male");
		MlaDTO mla42 = new MlaDTO("Priyank M. Kharge", 47, "Chittapur", "INC", false, "Male");
		MlaDTO mla43 = new MlaDTO("Narasimhanayak", 42, "Shorapur", "BJP", false, "Male");
		MlaDTO mla44 = new MlaDTO("Sharanabasappa Gouda Darshanapur", 52, "Shahapur", "INC", false, "Male");
		MlaDTO mla45 = new MlaDTO("Venkatreddy Mudnal", 58, "Yadgir", "BJP", false, "Male");
		MlaDTO mla46 = new MlaDTO("Naganagowda Kandukar", 53, "Gurmitkal", "JDS", false, "Male");
		MlaDTO mla47 = new MlaDTO("Sharanu Salagar", 59, "Basavakalyan", "BJP", false, "Male");
		MlaDTO mla48 = new MlaDTO("Rajshekar Basavaraj Patil", 54, "Homnabad", "INC", false, "Male");
		MlaDTO mla49 = new MlaDTO("Bandeppa Kashempur", 58, "Bidar South", "JDS", false, "Male");
		MlaDTO mla50 = new MlaDTO("Rahim Khan", 53, "Bidar", "INC", false, "Male");
		MlaDTO mla51 = new MlaDTO("Eshwara Bhimanna Khandre", 50, "Bhalki", "INC", false, "Male");
		MlaDTO mla52 = new MlaDTO("Prabhu Chavhan", 58, "Aurad", "BJP", false, "Male");
		MlaDTO mla53 = new MlaDTO("Basanagouda Daddal", 57, "Raichur Rural", "INC", false, "Male");
		MlaDTO mla54 = new MlaDTO("Dr.Shivaraj Patil S", 56, "Raichur", "BJP", false, "Male");
		MlaDTO mla55 = new MlaDTO("Raja Venkatappa Nayak", 65, "Manvi", "JDS", false, "Male");
		MlaDTO mla56 = new MlaDTO("Shivanagouda Naik", 67, "Devadurga", "BJP", false, "Male");
		MlaDTO mla57 = new MlaDTO("D.S.Hoolageri", 45, "Lingsugur", "INC", false, "Male");
		MlaDTO mla58 = new MlaDTO("Venkatrao Nadagouda", 48, "Sindhanur", "JDS", false, "Male");
		MlaDTO mla59 = new MlaDTO("Basanagouda Turvihal", 50, "Maski", "INC", false, "Male");
		MlaDTO mla60 = new MlaDTO("Amaregouda Linganagouda Patil Bayyapur", 52, "Kushtagi", "INC", false, "Male");
		MlaDTO mla61 = new MlaDTO("Basavaraj Dhadesugur", 58, "Kanakagiri", "BJP", false, "Male");
		MlaDTO mla62 = new MlaDTO("Paranna Munavalli", 44, "Gangawati", "BJP", false, "Male");
		MlaDTO mla63 = new MlaDTO("Achar Halappa Basappa", 49, "Yelburga", "BJP", false, "Male");
		MlaDTO mla64 = new MlaDTO("K.Raghavendra Basavaraj Hitnal", 45, "Koppal", "INC", false, "Male");
		MlaDTO mla65 = new MlaDTO("Ramappa Lamani", 42, "Shirahatti", "BJP", false, "Male");
		MlaDTO mla66 = new MlaDTO("H.K.Patil", 48, "Gadag", "INC", false, "Male");
		MlaDTO mla67 = new MlaDTO("Kalakappa Bandi", 49, "Ron", "BJP", false, "Male");
		MlaDTO mla68 = new MlaDTO("C.C.Patil", 40, "Nargund", "BJP", false, "Male");
		MlaDTO mla69 = new MlaDTO("Patil Munenakoppa Shankar", 47, "Navalgund", "BJP", false, "Male");
		MlaDTO mla70 = new MlaDTO("Kusuma Shivalli", 42, "Kundgol", "INC", false, "Female");
		MlaDTO mla71 = new MlaDTO("Amrupayyappa Desai", 43, "Dharwad", "BJP", false, "Male");
		MlaDTO mla72 = new MlaDTO("Abbayya Prasad", 47, "Hubli-Dharwad-East", "INC", false, "Male");
		MlaDTO mla73 = new MlaDTO("Jagadish Shettar", 65, "Hubli-Dharwad-Central", "BJP", false, "Male");
		MlaDTO mla74 = new MlaDTO("Aravind Bellad", 68, "Hubli-Dharwad-West", "BJP", false, "Male");
		MlaDTO mla75 = new MlaDTO("C.M.Nimbannavar", 69, "Kalghatgi", "BJP", false, "Male");
		MlaDTO mla76 = new MlaDTO("R.V.Deshapande", 62, "Haliyal", "INC", false, "Male");
		MlaDTO mla77 = new MlaDTO("Roopali Naik", 63, "Karwar", "BJP", false, "Female");
		MlaDTO mla78 = new MlaDTO("Dinakar Keshav Shetty", 67, "Kumta", "BJP", false, "Male");
		MlaDTO mla79 = new MlaDTO("Sunil Biliya Naik", 62, "Bhatkal", "BJP", false, "Male");
		MlaDTO mla80 = new MlaDTO("Vishweshwar Hegde Kageri", 63, "Sirsi", "BJP", false, "Male");
		MlaDTO mla81 = new MlaDTO("Arbail Shivaram Hebbar", 67, "Yellapur", "BJP", false, "Male");
		MlaDTO mla82 = new MlaDTO("Srinivas Mane", 69, "Hangal", "INC", false, "Male");
		MlaDTO mla83 = new MlaDTO("Basavaraj Bommai", 67, "Shiggaon", "BJP", false, "Male");
		MlaDTO mla84 = new MlaDTO("Neharu Olekar", 36, "Haveri (SC)", "BJP", false, "Male");
		MlaDTO mla85 = new MlaDTO("Ballary Virupakshappa Rudrappa", 48, "Byadgi", "BJP", false, "Male");
		MlaDTO mla86 = new MlaDTO("B.C.Patil", 45, "Hirekerur", "BJP", false, "Male");
		MlaDTO mla87 = new MlaDTO("Arunkumar Guththur", 42, "Ranibennur", "BJP", false, "Male");
		MlaDTO mla88 = new MlaDTO("P.T.Parameshwar Naik", 43, "Hadagalli", "INC", false, "Male");
		MlaDTO mla89 = new MlaDTO("L.B.P. Bheemanaik", 49, "Hagaribommanahalli", "INC", false, "Male");
		MlaDTO mla90 = new MlaDTO("Anand Singh", 47, "Vijayanagara", "BJP", false, "Male");
		MlaDTO mla91 = new MlaDTO("J.N.Ganesh", 52, "Kampli", "INC", false, "Male");
		MlaDTO mla92 = new MlaDTO("M.S.Somalingappa", 53, "Siruguppa", "BJP", false, "Male");
		MlaDTO mla93 = new MlaDTO("B.Nagendra", 59, "Bellary Rural", "INC", false, "Male");
		MlaDTO mla94 = new MlaDTO("G.Somashekara Reddy", 47, "Bellary City", "BJP", false, "Male");
		MlaDTO mla95 = new MlaDTO("E.Tukaram", 48, "Sandur", "INC", false, "Male");
		MlaDTO mla96 = new MlaDTO("N.Y.Gopalakrishna", 43, "Kudligi", "BJP", false, "Male");
		MlaDTO mla97 = new MlaDTO("B.Sreeramulu", 39, "Molakalmuru", "BJP", false, "Male");
		MlaDTO mla98 = new MlaDTO("T.Raghumurthy", 58, "Challakere", "INC", false, "Male");
		MlaDTO mla99 = new MlaDTO("G.H.Thippareddy", 57, "Chitradurga", "BJP", false, "Male");
		MlaDTO mla100 = new MlaDTO("K.Poornima", 53, "Hiriyur", "BJP", false, "Female");
		MlaDTO mla101 = new MlaDTO("Gulhatty D.Shekhar", 54, "Hosadurga", "BJP", false, "Male");
		MlaDTO mla102 = new MlaDTO("M.Chandrappa", 55, "Holalkere", "BJP", false, "Male");
		MlaDTO mla103 = new MlaDTO("S.V.Ramachandra", 59, "Jagalur", "BJP", false, "Male");
		MlaDTO mla104 = new MlaDTO("G.Karunakara Reddy", 68, "Harapanahalli", "BJP", false, "Male");
		MlaDTO mla105 = new MlaDTO("S.Ramappa", 57, "Harihar", "INC", false, "Male");
		MlaDTO mla106 = new MlaDTO("S.A.Ravindranath", 58, "Davanagere North", "BJP", false, "Male");
		MlaDTO mla107 = new MlaDTO("Shamanur Shivashankarappa", 57, "Davanagere South", "INC", false, "Male");
		MlaDTO mla108 = new MlaDTO("N.Linganna", 65, "Mayakonda", "BJP", false, "Male");
		MlaDTO mla109 = new MlaDTO("K.Madal Veerupakshappa", 51, "Channagiri", "BJP", false, "Male");
		MlaDTO mla110 = new MlaDTO("M.P.Renukacharya", 49, "Honnali", "BJP", false, "Male");
		MlaDTO mla111 = new MlaDTO("K.B.Ashok Naik", 65, "Shimoga Rural", "BJP", false, "Male");
		MlaDTO mla112 = new MlaDTO("B.K.Sangameshwara", 48, "Bhadravati", "INC", false, "Male");
		MlaDTO mla113 = new MlaDTO("K.S.Eshwarappa", 44, "Shimoga", "BJP", false, "Male");
		MlaDTO mla114 = new MlaDTO("Araga Jnanendra", 56, "Tirthahalli", "BJP", false, "Male");
		MlaDTO mla115 = new MlaDTO("B.S.Yeddyurappa", 57, "Shikaripura", "BJP", false, "Male");
		MlaDTO mla116 = new MlaDTO("Kumar Bangarappa", 53, "Soraba", "BJP", false, "Male");
		MlaDTO mla117 = new MlaDTO("Hartalu Halappa", 59, "Sagar", "BJP", false, "Male");
		MlaDTO mla118 = new MlaDTO("B.M.Sukumar Shetty", 40, "Baindur", "BJP", false, "Male");
		MlaDTO mla119 = new MlaDTO("Halady Srinivas Shetty", 50, "Kundapura", "BJP", false, "Male");
		MlaDTO mla120 = new MlaDTO("K.Raghupati Bhat", 60, "Udupi", "BJP", false, "Male");
		MlaDTO mla121 = new MlaDTO("Lalaji Mendon", 45, "Kapu", "BJP", false, "Male");
		MlaDTO mla122 = new MlaDTO("V.Sunil Kumar", 55, "Karkal", "BJP", false, "Male");
		MlaDTO mla123 = new MlaDTO("T.D.Rajegowda", 65, "Sringeri", "INC", false, "Male");
		MlaDTO mla124 = new MlaDTO("M.P.Kumaraswamy", 55, "Mudigere", "BJP", false, "Male");
		MlaDTO mla125 = new MlaDTO("C.T.Ravi", 77, "Chikmagalur", "BJP", false, "Male");
		MlaDTO mla126 = new MlaDTO("D.S.Suresh", 65, "Tarikere", "BJP", false, "Male");
		MlaDTO mla127 = new MlaDTO("Belliprakash", 49, "Kadur", "BJP", false, "Male");
		MlaDTO mla128 = new MlaDTO("J.C.Madhuswamy", 48, "Chiknayakanhalli", "BJP", false, "Male");
		MlaDTO mla129 = new MlaDTO("B.C.Nagesh", 53, "Tiptur", "BJP", false, "Male");
		MlaDTO mla130 = new MlaDTO("Jayaram A S", 51, "Turuvekere", "BJP", false, "Male");
		MlaDTO mla131 = new MlaDTO("Dr.H.D.Ranganath", 47, "Kunigal", "INC", false, "Male");
		MlaDTO mla132 = new MlaDTO("G.B.Jyothi Ganesh", 49, "Tumkur City", "BJP", false, "Male");
		MlaDTO mla133 = new MlaDTO("D.C.Gowrishankar", 47, "Tumkur Rural", "JDS", false, "Male");
		MlaDTO mla134 = new MlaDTO("Dr.G.Parameshwara", 43, "Koratagere", "INC", false, "Male");
		MlaDTO mla135 = new MlaDTO("S.R.Srinivas", 42, "Gubbi", "JDS", false, "Male");
		MlaDTO mla136 = new MlaDTO("C.M.Rajesh Gowda", 50, "Sira", "BJP", false, "Male");
		MlaDTO mla137 = new MlaDTO("Venkata Ramanappa", 47, "Pavagada", "INC", false, "Male");
		MlaDTO mla138 = new MlaDTO("M.V.Veerabhadraiah", 43, "Madhugiri", "JDS", false, "Male");
		MlaDTO mla139 = new MlaDTO("N.H.Shivashankara Reddy", 58, "Gauribidanur", "INC", false, "Male");
		MlaDTO mla140 = new MlaDTO("S.N.Subbareddy", 57, "Bagepalli", "INC", false, "Male");
		MlaDTO mla141 = new MlaDTO("K.Sudhakar", 43, "Chikkaballapur", "BJP", false, "Male");
		MlaDTO mla142 = new MlaDTO("V. Muniyappa", 60, "Sidlaghatta", "INC", false, "Male");
		MlaDTO mla143 = new MlaDTO("J.K.Krishnareddy", 67, "Chintamani", "JDS", false, "Male");
		MlaDTO mla144 = new MlaDTO("K.R.Rameshkumar", 68, "Srinivasapur", "INC", false, "Male");
		MlaDTO mla145 = new MlaDTO("H.Nagesh", 55, "Mulbagal", "IND", true, "Male");
		MlaDTO mla146 = new MlaDTO("M. Roopakala", 47, "Kolar Gold Field", "INC", false, "Female");
		MlaDTO mla147 = new MlaDTO("S.N.Narayanaswamy", 64, "Bangarapet", "INC", false, "Male");
		MlaDTO mla148 = new MlaDTO("K.Srinivasa Gowda", 58, "Kolar", "JDS", false, "Male");
		MlaDTO mla149 = new MlaDTO("K.Y.Nanjegowda", 65, "Malur", "INC", false, "Male");
		MlaDTO mla150 = new MlaDTO("S.R.Vishwanath", 55, "Yelahanka", "BJP", false, "Male");
		MlaDTO mla151 = new MlaDTO("Byrathi Basavaraj", 48, "K.R.Pura", "BJP", false, "Male");
		MlaDTO mla152 = new MlaDTO("Krishna Byre Gowda", 65, "Byatarayanapura", "INC", false, "Male");
		MlaDTO mla153 = new MlaDTO("S.T.Somashekar", 64, "Yeshwanthpur", "BJP", false, "Male");
		MlaDTO mla154 = new MlaDTO("Munirathna", 62, "Rajarajeshwari Nagar", "BJP", false, "Male");
		MlaDTO mla155 = new MlaDTO("R.Manjunatha", 60, "Dasarahalli", "JDS", false, "Male");
		MlaDTO mla156 = new MlaDTO("K.Gopalaiah", 58, "Mahalakshmi Layout", "BJP", false, "Male");
		MlaDTO mla157 = new MlaDTO("Dr.C.N.Ashwath Narayan", 42, "Malleshwaram", "BJP", false, "Male");
		MlaDTO mla158 = new MlaDTO("Suresha BS", 47, "Hebbal", "INC", false, "Male");
		MlaDTO mla159 = new MlaDTO("Akhanda Srinivas Murthy", 47, "Pulakeshinagar", "INC", false, "Male");
		MlaDTO mla160 = new MlaDTO("K.J.George", 53, "Sarvagnanagar", "INC", false, "Male");
		MlaDTO mla161 = new MlaDTO("S.Raghu", 57, "C.V.Raman Nagar", "BJP", false, "Male");
		MlaDTO mla162 = new MlaDTO("Rizwan Arshad", 48, "Shivajinagar", "INC", false, "Male");
		MlaDTO mla163 = new MlaDTO("N.A.Haris", 53, "Shanti Nagar", "INC", false, "Male");
		MlaDTO mla164 = new MlaDTO("Dinesh Gundu Rao", 65, "Gandhi Nagar", "INC", false, "Male");
		MlaDTO mla165 = new MlaDTO("S.Suresh Kumar", 75, "Rajaji Nagar", "BJP", false, "Male");
		MlaDTO mla166 = new MlaDTO("V.Somanna", 72, "Govindraj Nagar", "BJP", false, "Male");
		MlaDTO mla167 = new MlaDTO("M.Krishnappa", 62, "Vijay Nagar", "INC", false, "Male");
		MlaDTO mla168 = new MlaDTO("Zameer Ahmed Khan", 35, "Chamrajpet", "INC", false, "Male");
		MlaDTO mla169 = new MlaDTO("Uday B.Garudachar", 64, "Chickpet", "BJP", false, "Male");
		MlaDTO mla170 = new MlaDTO("L.A.Ravi Subramanya	", 53, "Basavanagudi", "BJP", false, "Male");
		MlaDTO mla171 = new MlaDTO("R.Ashoka", 58, "Padmanaba Nagar", "BJP", false, "Male");
		MlaDTO mla172 = new MlaDTO("Ramalinga Reddy", 57, "B.T.M. Layout", "INC", false, "Male");
		MlaDTO mla173 = new MlaDTO("Soumya Reddy", 52, "Jayanagar", "INC", false, "Female");
		MlaDTO mla174 = new MlaDTO("Aravind Limbavali", 47, "Mahadevapura", "BJP", false, "Male");
		MlaDTO mla175 = new MlaDTO("M Satish Reddy", 46, "Bommanahalli", "BJP", false, "Male");
		MlaDTO mla176 = new MlaDTO("M.Krishnappa", 59, "Bangalore South", "BJP", false, "Male");
		MlaDTO mla177 = new MlaDTO("B.Shivanna", 52, "Anekal", "INC", false, "Male");
		MlaDTO mla178 = new MlaDTO("Sharath Kumar Bachegowda", 56, "Hoskote", "IND", true, "Male");
		MlaDTO mla179 = new MlaDTO("Nisarga Narayanaswamy L.N", 58, "Devanahalli", "JDS", false, "Male");
		MlaDTO mla180 = new MlaDTO("T.Venkataramanaiah", 48, "Doddaballapur", "INC", false, "Male");
		MlaDTO mla181 = new MlaDTO("Dr.K.Srinavasamurthy", 42, "Nelamangala", "JDS", false, "Male");
		MlaDTO mla182 = new MlaDTO("A.Manjunath", 65, "Magadi", "JDS", false, "Male");
		MlaDTO mla183 = new MlaDTO("Anitha Kumaraswamy", 53, "Ramanagara", "JDS", false, "Female");
		MlaDTO mla184 = new MlaDTO("D.K.Shivakumar", 52, "Kanakapura", "INC", false, "Male");
		MlaDTO mla185 = new MlaDTO("H.D.Kumaraswamy", 56, "Channapatna", "JDS", false, "Male");
		MlaDTO mla186 = new MlaDTO("Dr.K.Annadani", 58, "Malavalli", "JDS", false, "Male");
		MlaDTO mla187 = new MlaDTO("D.C.Thammanna", 54, "Maddur", "JDS", false, "Male");
		MlaDTO mla188 = new MlaDTO("C.S.Puttaraju", 61, "Melukote", "JDS", false, "Male");
		MlaDTO mla189 = new MlaDTO("M.Srinivas", 69, "Mandya", "JDS", false, "Male");
		MlaDTO mla190 = new MlaDTO("Ravindra Srikantaiah", 58, "Shrirangapattana", "JDS", false, "Male");
		MlaDTO mla191 = new MlaDTO("Suresh Gowda", 54, "Nagamangala", "JDS", false, "Male");
		MlaDTO mla192 = new MlaDTO("Narayana Gowda", 48, "Krishnarajpet", "BJP", false, "Male");
		MlaDTO mla193 = new MlaDTO("C.N.Balakrishna", 49, "Shravanabelagola", "JDS", false, "Male");
		MlaDTO mla194 = new MlaDTO("K.M.Shivalingegowda", 42, "Arsikere", "JDS", false, "Male");
		MlaDTO mla195 = new MlaDTO("K.S.Lingesha", 46, "	Belur", "JDS", false, "Male");
		MlaDTO mla196 = new MlaDTO("Preetham J.Gowda", 68, "Hassan", "BJP", false, "Male");
		MlaDTO mla197 = new MlaDTO("H.D.Revanna", 62, "Holenarasipur", "JDS", false, "Male");
		MlaDTO mla198 = new MlaDTO("A.T.Ramaswamy", 50, "Arkalgud", "JDS", false, "Male");
		MlaDTO mla199 = new MlaDTO("H.K.Kumaraswamy", 57, "Sakleshpur", "JDS", false, "Male");
		MlaDTO mla200 = new MlaDTO("Harish Poonja", 52, "Belthangady", "BJP", false, "Male");
		MlaDTO mla201 = new MlaDTO("Umanatha A. Kotian", 58, "Moodabidri", "BJP", false, "Male");
		MlaDTO mla202 = new MlaDTO("Bharath Shetty", 65, "Mangalore City North", "BJP", false, "Male");
		MlaDTO mla203 = new MlaDTO("D.Vedavyas Kamath", 49, "Mangalore City South", "BJP", false, "Male");
		MlaDTO mla204 = new MlaDTO("U.T.Khader", 55, "Mangalore", "INC", false, "Male");
		MlaDTO mla205 = new MlaDTO("Rajesh Naik", 46, "	Bantval", "BJP", false, "Male");
		MlaDTO mla206 = new MlaDTO("Sanjeeva Matandoor", 48, "Puttur", "BJP", false, "Male");
		MlaDTO mla207 = new MlaDTO("Angara S", 50, "Sullia", "BJP", false, "Male");
		MlaDTO mla208 = new MlaDTO("Appachu Ranjan", 61, "Madikeri", "BJP", false, "Male");
		MlaDTO mla209 = new MlaDTO("K.G.Bopaiah", 55, "Virajpet", "BJP", false, "Male");
		MlaDTO mla210 = new MlaDTO("K.Mahadeva", 54, "Periyapatna", "JDS", false, "Male");
		MlaDTO mla211 = new MlaDTO("S.R.Mahesh", 46, "Krishnarajanagara", "JDS", false, "Male");
		MlaDTO mla212 = new MlaDTO("H.P.Manjunath", 38, "Hunsuru", "INC", false, "Male");
		MlaDTO mla213 = new MlaDTO("Anil Kumar C.", 39, "Heggadadevankote", "INC", false, "Male");
		MlaDTO mla214 = new MlaDTO("Harshavardhan B.", 44, "Nanjangud", "BJP", false, "Male");
		MlaDTO mla215 = new MlaDTO("GT Devegowda", 47, "Chamundeshwari", "JDS", false, "Male");
		MlaDTO mla216 = new MlaDTO("S.A.Ramadas", 43, "Krishnaraja", "BJP", false, "Male");
		MlaDTO mla217 = new MlaDTO("L.Nagendra", 55, "Chamaraja", "BJP", false, "Male");
		MlaDTO mla218 = new MlaDTO("Tanveer Sait", 58, "Narasimharaja", "INC", false, "Male");
		MlaDTO mla219 = new MlaDTO("Yathindra S.", 52, "Varuna", "INC", false, "Male");
		MlaDTO mla220 = new MlaDTO("Ashvin Kumar M.", 59, "T Narasipura", "JDS", false, "Male");
		MlaDTO mla221 = new MlaDTO("R.Narendra", 56, "Hanur", "INC", false, "Male");
		MlaDTO mla222 = new MlaDTO("N.Mahesh", 53, "Kollegal", "BSP", false, "Male");
		MlaDTO mla223 = new MlaDTO("C.Puttarangashetty", 62, "Chamrajanagar", "INC", false, "Male");
		MlaDTO mla224 = new MlaDTO("C.S.Niranjan Kumar", 58, "Gundlupet", "BJP", false, "Male");

		Collection<MlaDTO> mlas = new ArrayList<>();
		mlas.add(mla1);
		mlas.add(mla2);
		mlas.add(mla3);
		mlas.add(mla4);
		mlas.add(mla5);
		mlas.add(mla6);
		mlas.add(mla7);
		mlas.add(mla8);
		mlas.add(mla9);
		mlas.add(mla10);
		mlas.add(mla11);
		mlas.add(mla12);
		mlas.add(mla13);
		mlas.add(mla14);
		mlas.add(mla15);
		mlas.add(mla16);
		mlas.add(mla17);
		mlas.add(mla18);
		mlas.add(mla19);
		mlas.add(mla20);
		mlas.add(mla21);
		mlas.add(mla22);
		mlas.add(mla23);
		mlas.add(mla24);
		mlas.add(mla25);
		mlas.add(mla26);
		mlas.add(mla27);
		mlas.add(mla28);
		mlas.add(mla29);
		mlas.add(mla30);
		mlas.add(mla31);
		mlas.add(mla32);
		mlas.add(mla33);
		mlas.add(mla34);
		mlas.add(mla35);
		mlas.add(mla36);
		mlas.add(mla37);
		mlas.add(mla38);
		mlas.add(mla39);
		mlas.add(mla40);
		mlas.add(mla41);
		mlas.add(mla42);
		mlas.add(mla43);
		mlas.add(mla44);
		mlas.add(mla45);
		mlas.add(mla46);
		mlas.add(mla47);
		mlas.add(mla48);
		mlas.add(mla49);
		mlas.add(mla50);
		mlas.add(mla51);
		mlas.add(mla52);
		mlas.add(mla53);
		mlas.add(mla54);
		mlas.add(mla55);
		mlas.add(mla56);
		mlas.add(mla57);
		mlas.add(mla58);
		mlas.add(mla59);
		mlas.add(mla60);
		mlas.add(mla61);
		mlas.add(mla62);
		mlas.add(mla63);
		mlas.add(mla64);
		mlas.add(mla65);
		mlas.add(mla66);
		mlas.add(mla67);
		mlas.add(mla68);
		mlas.add(mla69);
		mlas.add(mla70);
		mlas.add(mla71);
		mlas.add(mla72);
		mlas.add(mla73);
		mlas.add(mla74);
		mlas.add(mla75);
		mlas.add(mla76);
		mlas.add(mla77);
		mlas.add(mla78);
		mlas.add(mla79);
		mlas.add(mla80);
		mlas.add(mla81);
		mlas.add(mla82);
		mlas.add(mla83);
		mlas.add(mla84);
		mlas.add(mla85);
		mlas.add(mla86);
		mlas.add(mla87);
		mlas.add(mla88);
		mlas.add(mla89);
		mlas.add(mla90);
		mlas.add(mla91);
		mlas.add(mla92);
		mlas.add(mla93);
		mlas.add(mla94);
		mlas.add(mla95);
		mlas.add(mla96);
		mlas.add(mla97);
		mlas.add(mla98);
		mlas.add(mla99);
		mlas.add(mla100);
		mlas.add(mla101);
		mlas.add(mla102);
		mlas.add(mla103);
		mlas.add(mla104);
		mlas.add(mla105);
		mlas.add(mla106);
		mlas.add(mla107);
		mlas.add(mla108);
		mlas.add(mla109);
		mlas.add(mla110);
		mlas.add(mla111);
		mlas.add(mla112);
		mlas.add(mla113);
		mlas.add(mla114);
		mlas.add(mla115);
		mlas.add(mla116);
		mlas.add(mla117);
		mlas.add(mla118);
		mlas.add(mla119);
		mlas.add(mla120);
		mlas.add(mla121);
		mlas.add(mla122);
		mlas.add(mla123);
		mlas.add(mla124);
		mlas.add(mla125);
		mlas.add(mla126);
		mlas.add(mla127);
		mlas.add(mla128);
		mlas.add(mla129);
		mlas.add(mla130);
		mlas.add(mla131);
		mlas.add(mla132);
		mlas.add(mla133);
		mlas.add(mla134);
		mlas.add(mla135);
		mlas.add(mla136);
		mlas.add(mla137);
		mlas.add(mla138);
		mlas.add(mla139);
		mlas.add(mla140);
		mlas.add(mla141);
		mlas.add(mla142);
		mlas.add(mla143);
		mlas.add(mla144);
		mlas.add(mla145);
		mlas.add(mla146);
		mlas.add(mla147);
		mlas.add(mla148);
		mlas.add(mla149);
		mlas.add(mla150);
		mlas.add(mla151);
		mlas.add(mla152);
		mlas.add(mla153);
		mlas.add(mla154);
		mlas.add(mla155);
		mlas.add(mla156);
		mlas.add(mla157);
		mlas.add(mla158);
		mlas.add(mla159);
		mlas.add(mla160);
		mlas.add(mla161);
		mlas.add(mla162);
		mlas.add(mla163);
		mlas.add(mla164);
		mlas.add(mla165);
		mlas.add(mla166);
		mlas.add(mla167);
		mlas.add(mla168);
		mlas.add(mla169);
		mlas.add(mla170);
		mlas.add(mla171);
		mlas.add(mla172);
		mlas.add(mla173);
		mlas.add(mla174);
		mlas.add(mla175);
		mlas.add(mla176);
		mlas.add(mla177);
		mlas.add(mla178);
		mlas.add(mla179);
		mlas.add(mla180);
		mlas.add(mla181);
		mlas.add(mla182);
		mlas.add(mla183);
		mlas.add(mla184);
		mlas.add(mla185);
		mlas.add(mla186);
		mlas.add(mla187);
		mlas.add(mla188);
		mlas.add(mla189);
		mlas.add(mla190);
		mlas.add(mla191);
		mlas.add(mla192);
		mlas.add(mla193);
		mlas.add(mla194);
		mlas.add(mla195);
		mlas.add(mla196);
		mlas.add(mla197);
		mlas.add(mla198);
		mlas.add(mla199);
		mlas.add(mla200);
		mlas.add(mla201);
		mlas.add(mla202);
		mlas.add(mla203);
		mlas.add(mla204);
		mlas.add(mla205);
		mlas.add(mla206);
		mlas.add(mla207);
		mlas.add(mla208);
		mlas.add(mla209);
		mlas.add(mla210);
		mlas.add(mla211);
		mlas.add(mla212);
		mlas.add(mla213);
		mlas.add(mla214);
		mlas.add(mla215);
		mlas.add(mla216);
		mlas.add(mla217);
		mlas.add(mla218);
		mlas.add(mla219);
		mlas.add(mla220);
		mlas.add(mla221);
		mlas.add(mla222);
		mlas.add(mla223);
		mlas.add(mla224);

		System.out.println("Toatal MLA's:" + mlas.size());

		System.out.println("---------MLA's Age is greater than 50-------------");

		mlas.stream().filter(e1 -> e1.getAge() > 50).collect(Collectors.toList())
				.forEach(e1 -> System.out.println(e1.getName()));

		System.out.println("---------MLA's Age is lesser than 50---------------");

		mlas.stream().filter(e2 -> e2.getAge() < 50).collect(Collectors.toList())
				.forEach(e2 -> System.out.println(e2.getName()));

		System.out.println("---------All Male MLA's-----------------");

		mlas.stream().filter(e3 -> e3.getGender().contains("Male")).collect(Collectors.toList())
				.forEach(e3 -> System.out.println(e3.getName()));

		System.out.println("---------All Female MLA's-----------------");

		mlas.stream().filter(e4 -> e4.getGender().contains("Female")).collect(Collectors.toList())
				.forEach(e4 -> System.out.println(e4.getName()));

		System.out.println("----------Sorted collection by Party in ascending order-------------");

		mlas.stream().collect(Collectors.toList()).stream()
				.sorted((ref1, ref2) -> ref1.getParty().compareTo(ref2.getParty())).forEach(e5 -> System.out
						.println(" Party name: " + e5.getParty() + "  " + " MLA's Name: " + e5.getName()));

		System.out.println("----------Sorted collection by Name in ascending order------------");

		mlas.stream().collect(Collectors.toList()).stream()
				.sorted((ref1, ref2) -> ref1.getName().compareTo(ref2.getName()))
				.forEach(e6 -> System.out.println("MLA's Name:" + e6.getName()));

		System.out.println("---------Sorted collection by Age in descending order--------------");

		mlas.stream().collect(Collectors.toList()).stream()
				.sorted((ref1, ref2) -> Integer.compare(ref2.getAge(), ref1.getAge()))
				.forEach(e7 -> System.out.println("Age: " + e7.getAge() + "  " + " MLA's Name: " + e7.getName()));

		System.out.println("----------------Collect MLA's by each Constituency-------------");

		mlas.stream().filter(e -> e.getConstituency().equals("Hungund")).collect(Collectors.toList())
				.forEach(e -> System.out.println("MLA of Hungund:" + e.getName()));

		System.out.println("----------------Collect all MLA's By BJP Party-----------------");

		mlas.stream().filter(e -> e.getParty().equals("BJP")).collect(Collectors.toList())
				.forEach(e -> System.out.println("MLA's of BJP Party:" + e.getName()));

		System.out.println("----------------Find Unique Parties-----------------------");

		mlas.stream().map(e10 -> e10.getParty()).collect(Collectors.toSet()).forEach(e10 -> System.out.println(e10));

		System.out.println("----------------Find Independent MLA's----------------------");

		mlas.stream().filter(e11 -> e11.getParty().contains("IND")).collect(Collectors.toList())
				.forEach(e11 -> System.out.println(e11.getName()));

		System.out.println("-------------Find all MLA's Age >50 and Party is BJP----------");

		mlas.stream().filter(e -> e.getAge() > 50 && e.getParty().matches("BJP")).collect(Collectors.toList())
				.forEach(e -> System.out.println("MLA's:" + e.getName() + " " + " Party is:" + e.getParty()));

	}

}
